# Generated by Django 4.2.3 on 2023-07-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitee_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
