# Generated by Django 4.2.3 on 2023-07-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_invitation_invitee_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
