# Generated by Django 4.2.3 on 2023-07-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invited_by_profiles', to='users.profile'),
        ),
    ]
