# Generated by Django 4.2.3 on 2023-07-16 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_invited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_received', to='users.profile'),
        ),
    ]
