# Generated by Django 4.2.3 on 2023-07-16 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_profile_invited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invited_by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
