# Generated by Django 4.2.3 on 2023-07-16 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_alter_profile_invited_by_alter_profile_invited_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='sub_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
