# Generated by Django 4.2.3 on 2023-07-16 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_invited_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='invited_users',
        ),
    ]
