# Generated by Django 4.2.3 on 2023-09-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'כללי'), ('career', 'קריירה'), ('personal_growth', 'התפתחות אישית'), ('relationship', 'זוגיות'), ('creative_thinking', 'חשיבה יצירתית')], max_length=20)),
                ('task_type', models.CharField(choices=[('survey', 'שאלון'), ('fill_in_the_blanks', 'השלמת משפטים'), ('text_or_image', 'רגשות מטקסט או תמונה')], max_length=20)),
            ],
        ),
    ]
