# Generated by Django 4.2.3 on 2023-07-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_question_remove_interviewed_questionnaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scalingquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('scaling', 'Scaling'), ('rating', 'Rating')], default='regular', max_length=20),
        ),
        migrations.DeleteModel(
            name='RatingQuestion',
        ),
        migrations.DeleteModel(
            name='ScalingQuestion',
        ),
    ]
