# Generated by Django 4.2.3 on 2023-07-21 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaires', '0004_remove_question_question_type_remove_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='author',
        ),
        migrations.AddField(
            model_name='interviewer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.interviewer'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='explanation',
            field=models.TextField(),
        ),
    ]
