# Generated by Django 4.2.3 on 2023-07-21 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaires', '0005_remove_questionnaire_author_interviewer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='interviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.interviewer'),
            preserve_default=False,
        ),
    ]
