# Generated by Django 4.2.3 on 2023-09-16 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('allows_multiple_responses', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Obj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_type', models.CharField(choices=[('title', 'כותרת'), ('explanation', 'הסבר'), ('image', 'תמונה'), ('divider', 'מפצל'), ('hints', 'רמזים'), ('open_question', 'שאלה פתוחה'), ('single_choice', 'שאלת בחירה בודדת'), ('multiple_choice', 'שאלת בחירה מרובה'), ('rating', 'שאלת דירוג'), ('agreement', 'שאלת הצבה'), ('self_rating', 'שאלת דירוג עצמי'), ('self_choice', 'שאלת בחירה עצמית'), ('Completing', 'השלמת משפטים')], max_length=20)),
                ('content', models.TextField()),
                ('hierarchy_counter', models.CharField(blank=True, max_length=20)),
                ('hierarchy_position', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_objs', to='surveys.obj')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objs', to='surveys.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='FullAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('date_responed', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responder', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_question', to='surveys.obj')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_responder', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
