# Generated by Django 4.2.3 on 2023-09-16 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullanswer',
            name='date_responed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fullanswer',
            name='date_sent',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='FullTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=225)),
                ('sub_title', models.TextField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
