# Generated by Django 4.2.3 on 2023-07-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_questionnaire_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='explanation',
            field=models.TextField(null=True),
        ),
    ]
