# Generated by Django 4.2.3 on 2023-09-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_fulltask_category_fulltask_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltask',
            name='category',
            field=models.CharField(choices=[('general', 'כללי'), ('career', 'קריירה'), ('personal_growth', 'התפתחות אישית'), ('relationship', 'זוגיות'), ('creative_thinking', 'חשיבה יצירתית')], default='general', max_length=200),
        ),
        migrations.AlterField(
            model_name='fulltask',
            name='sub_category',
            field=models.CharField(choices=[('survey', 'שאלון'), ('fill_in_the_blanks', 'השלמת משפטים'), ('text_or_image', 'רגשות מטקסט או תמונה')], default='other', max_length=200),
        ),
    ]
