# Generated by Django 4.2.3 on 2023-07-23 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_questionset_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='creation_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='hints',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
