# Generated by Django 4.2.3 on 2023-07-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_questionnaire_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='set_type',
            field=models.CharField(choices=[('SIMPLE', 'שאלות פתוחות'), ('RATING', 'שאלות דירוג'), ('POSTING', 'שאלות הצבה'), ('CHOOSING', 'שאלות בחירה'), ('MULTY_CHOOSE', 'בחירה מרובה')], max_length=50),
        ),
    ]
