# Generated by Django 4.2.3 on 2023-09-16 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_fullanswer_date_responed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullanswer',
            name='answered_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.fulltask'),
        ),
    ]
