# Generated by Django 4.2.3 on 2023-07-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_questionset_hints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='set_type',
            field=models.CharField(choices=[('SIMPLE', 'שאלות פתוחות'), ('SIMPLE', 'שאלות סגורות'), ('RATING', 'שאלות דירוג'), ('POSTING', 'שאלות הצבה'), ('CHOOSING', 'שאלות בחירה'), ('MULTY_CHOOSE', 'בחירה מרובה'), ('SELF_RATING', ' דירוג עצמי')], max_length=50),
        ),
    ]
