# Generated by Django 4.2.3 on 2023-09-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_fullanswer_answered_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltask',
            name='content',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
