# Generated by Django 4.2.3 on 2023-07-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_alter_questionset_set_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='set_type',
            field=models.CharField(choices=[('SIMPLE_SHORT', ' שאלות פתוחות קצרות'), ('SIMPLE_LONG', ' שאלות פתוחות ארוכות'), ('CLOSE', 'שאלות סגורות'), ('RATING', 'שאלות דירוג'), ('POSTING', 'שאלות הצבה'), ('CHOOSING', 'שאלות בחירה'), ('MULTY_CHOOSE', 'בחירה מרובה'), ('SELF_RATING', ' דירוג עצמי')], max_length=50),
        ),
    ]
