# Generated by Django 4.2.3 on 2023-07-27 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0009_alter_questionset_set_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_type', models.CharField(choices=[('title', 'כותרת'), ('explanation', 'הסבר'), ('image', 'תמונה'), ('divider', 'מפצל'), ('hints', 'רמזים'), ('open_question', 'שאלה פתוחה'), ('single_choice', 'שאלת בחירה בודדת'), ('multiple_choice', 'שאלת בחירה מרובה'), ('rating', 'שאלת דירוג'), ('agreement', 'שאלת הצבה'), ('self_rating', 'שאלת דירוג עצמי'), ('self_choice', 'שאלת בחירה עצמית')], max_length=20)),
                ('content', models.TextField()),
                ('hierarchy_counter', models.CharField(blank=True, max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_objs', to='surveys.obj')),
            ],
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='questionnaire',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='related_question',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='survey_type',
        ),
        migrations.AddField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='answer',
            name='obj_temp_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answer_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='allows_multiple_responses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_responder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionSet',
        ),
        migrations.AddField(
            model_name='obj',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objs', to='surveys.questionnaire'),
        ),
    ]
