# Generated by Django 4.2.3 on 2023-07-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_obj_remove_questionset_questionnaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obj',
            name='hierarchy_position',
            field=models.IntegerField(default=0),
        ),
    ]
