# Generated by Django 4.2.3 on 2023-07-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_obj_hierarchy_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obj',
            name='hierarchy_position',
        ),
    ]
