# Generated by Django 4.2.3 on 2023-07-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_remove_obj_hierarchy_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='obj',
            name='hierarchy_position',
            field=models.IntegerField(default=0),
        ),
    ]
