# Generated by Django 4.2.3 on 2023-08-02 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_obj_hierarchy_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='quesiton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_question', to='surveys.obj'),
        ),
    ]
