# Generated by Django 4.2.3 on 2023-08-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_alter_answer_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='obj_temp_id',
        ),
    ]
