# Generated by Django 4.2.3 on 2023-08-02 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_remove_answer_obj_temp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='quesiton',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_question', to='surveys.obj'),
        ),
    ]
