# Generated by Django 4.2.3 on 2023-08-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_remove_answer_quesiton_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obj',
            name='obj_type',
            field=models.CharField(choices=[('title', 'כותרת'), ('explanation', 'הסבר'), ('image', 'תמונה'), ('divider', 'מפצל'), ('hints', 'רמזים'), ('open_question', 'שאלה פתוחה'), ('single_choice', 'שאלת בחירה בודדת'), ('multiple_choice', 'שאלת בחירה מרובה'), ('rating', 'שאלת דירוג'), ('agreement', 'שאלת הצבה'), ('self_rating', 'שאלת דירוג עצמי'), ('self_choice', 'שאלת בחירה עצמית'), ('Completing', 'השלמת משפטים')], max_length=20),
        ),
    ]
