# Generated by Django 4.2.3 on 2023-09-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_alter_fullanswer_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullanswer',
            old_name='created_date',
            new_name='date_sent',
        ),
        migrations.AddField(
            model_name='fullanswer',
            name='date_responed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
