# Generated by Django 4.2.3 on 2023-09-09 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_alter_fullanswer_date_responed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullanswer',
            name='date_responed',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fullanswer',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
