# Generated by Django 4.2.3 on 2023-07-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitation_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved')], default='waiting', max_length=20),
        ),
    ]
