# Generated by Django 4.2.3 on 2023-07-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_invitation_invitation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitation_status',
            field=models.CharField(choices=[('waiting', 'בהמתנה'), ('approved', 'בוצע')], default='waiting', max_length=20),
        ),
    ]
